
-- Table: BASIC_CUST_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.BASIC_CUST_DATA (
    CUST_ID INT PRIMARY KEY,
    IND_FN VARCHAR(50),
    IND_LN VARCHAR(50),
    ADDRESS VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE_NO VARCHAR(15),
    SALARY_PM DECIMAL(10, 2),
    CUST_IND_BUD DECIMAL(10, 2),
    NO_OF_DEPENDENTS INT,
    NOMINEE VARCHAR(100),
    CUST_ADHAR VARCHAR(12),
    CUST_PAN VARCHAR(10),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: EMP_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.EMP_DATA (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(100),
    EMP_EMAIL VARCHAR(100),
    NO_OF_CUST_DEALT INT,
    NO_OF_SALES INT,
    COMM_ON_SLS DECIMAL(5, 2),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: CASE_TABLE
CREATE TABLE BUDDIGA_DEVELOPERS.CASE_TABLE (
    CASE_ID INT PRIMARY KEY,
    EMP_ID INT,
    CUST_ID INT,
    QUERY TEXT,
    CASE_PRGRS TEXT,
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP,
    FOREIGN KEY (EMP_ID) REFERENCES EMP_DATA(EMP_ID),
    FOREIGN KEY (CUST_ID) REFERENCES BASIC_CUST_DATA(CUST_ID)
);

-- Table: PROJECTS_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.PROJECTS_DATA (
    PRJCT_ID INT PRIMARY KEY,
    PRJCT_NAME VARCHAR(100),
    PRJCT_ADDRESS VARCHAR(100),
    PRJCT_STATUS VARCHAR(50),
    PRJCT_POSESSION TIMESTAMP,
    NO_OF_TOWERS INT,
    NO_OF_FLOORS INT,
    PRJCT_AREA DECIMAL(10, 2),
    TOTAL_NO_OF_APTS INT,
    NO_OF_APTS_SOLD INT,
    NO_OF_APTS_AVL INT,
    DIST_FRM_ARPT DECIMAL(10, 2),
    DIST_FRM_RAIL DECIMAL(10, 2),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: PROPERTY_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.PROPERTY_DATA (
    PRPTY_ID INT PRIMARY KEY,
    PRJCT_ID INT,
    PRPTY_SQ_FT_AREA DECIMAL(10, 2),
    TYPE_OF_BHKS VARCHAR(20),
    PRICE_RANGE VARCHAR(50),
    PRPTY_FACING VARCHAR(50),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP,
    FOREIGN KEY (PRJCT_ID) REFERENCES PROJECTS_DATA(PRJCT_ID)
);

-- Table: FUNDS_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.FUNDS_DATA (
    FUND_ID INT PRIMARY KEY,
    PRJCT_ID INT,
    FUND_EST_TO_CMLT_PROJ DECIMAL(10, 2),
    FUND_SPNT_TILL_DT DECIMAL(10, 2),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP,
    FOREIGN KEY (PRJCT_ID) REFERENCES PROJECTS_DATA(PRJCT_ID)
);

-- Table: SALES_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.SALES_DATA (
    SALE_ID INT PRIMARY KEY,
    CUST_ID INT,
    EMP_ID INT,
    RVNUE_RCVD DECIMAL(10, 2),
    RVNUE_YET_TO_COME DECIMAL(10, 2),
    POSESSION_DATE_AGRD TIMESTAMP,
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP,
    FOREIGN KEY (CUST_ID) REFERENCES BASIC_CUST_DATA(CUST_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMP_DATA(EMP_ID)
);