
-- Table: BASIC_CUST_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.BASIC_CUST_DATA (
    CUST_ID INT PRIMARY KEY,
    IND_FN VARCHAR(50),
    IND_LN VARCHAR(50),
    ADDRESS VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE_NO VARCHAR(15),
    SALARY_PM DECIMAL(10, 2),
    CUST_IND_BUD DECIMAL(10, 2),
    NO_OF_DEPENDENTS INT,
    NOMINEE VARCHAR(100),
    CUST_ADHAR VARCHAR(12),
    CUST_PAN VARCHAR(10),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: EMP_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.EMP_DATA (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(100),
    EMP_EMAIL VARCHAR(100),
    NO_OF_CUST_DEALT INT,
    NO_OF_SALES INT,
    COMM_ON_SLS DECIMAL(100, 2),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: CASE_TABLE
CREATE TABLE BUDDIGA_DEVELOPERS.CASE_TABLE (
    CASE_ID INT PRIMARY KEY,
    EMP_ID INT,
    CUST_ID INT,
    QUERY TEXT,
    CASE_PRGRS VARCHAR(50),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: PROJECTS_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.PROJECTS_DATA (
    PRJCT_ID INT PRIMARY KEY,
    PRJCT_NAME VARCHAR(100),
    PRJCT_ADDRESS VARCHAR(100),
    PRJCT_STATUS VARCHAR(50),
    PRJCT_POSESSION TIMESTAMP,
    NO_OF_TOWERS INT,
    NO_OF_FLOORS INT,
    PRJCT_AREA DECIMAL(10, 2),
    TOTAL_NO_OF_APTS INT,
    NO_OF_APTS_SOLD INT,
    NO_OF_APTS_AVL INT,
    DIST_FRM_ARPT DECIMAL(10, 2),
    DIST_FRM_RAIL DECIMAL(10, 2),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: PROPERTY_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.PROPERTY_DATA (
    PRPTY_ID INT PRIMARY KEY,
    PRJCT_ID INT,
    PRPTY_SQ_FT_AREA DECIMAL(10, 2),
    TYPE_OF_BHKS VARCHAR(20),
    PRICE_RANGE VARCHAR(50),
    PRPTY_FACING VARCHAR(50),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: FUNDS_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.FUNDS_DATA (
    FUND_ID INT PRIMARY KEY,
    PRJCT_ID INT,
    FUND_EST_TO_CMLT_PROJ DECIMAL(10, 2),
    FUND_SPNT_TILL_DT DECIMAL(10, 2),
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);

-- Table: SALES_DATA
CREATE TABLE BUDDIGA_DEVELOPERS.SALES_DATA (
    SALE_ID INT PRIMARY KEY,
    CUST_ID INT,
    EMP_ID INT,
    RVNUE_RCVD DECIMAL(10, 2),
    RVNUE_YET_TO_COME DECIMAL(10, 2),
    POSESSION_DATE_AGRD TIMESTAMP,
    CRE_TS TIMESTAMP,
    UPDT_TS TIMESTAMP
);


-- Create sequence for BASIC_CUST_DATA
CREATE SEQUENCE BASIC_CUST_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create sequence for EMP_DATA
CREATE SEQUENCE EMP_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create sequence for CASE_TABLE
CREATE SEQUENCE CASE_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create sequence for PROJECTS_DATA
CREATE SEQUENCE PRJCT_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create sequence for PROPERTY_DATA
CREATE SEQUENCE PRPTY_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create sequence for FUNDS_DATA
CREATE SEQUENCE FUND_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create sequence for SALES_DATA
CREATE SEQUENCE SALE_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Insert data into BASIC_CUST_DATA
INSERT INTO BUDDIGA_DEVELOPERS.BASIC_CUST_DATA (CUST_ID, IND_FN, IND_LN, ADDRESS, EMAIL, PHONE_NO, SALARY_PM, CUST_IND_BUD, NO_OF_DEPENDENTS, NOMINEE, CUST_ADHAR, CUST_PAN, CRE_TS, UPDT_TS)
SELECT
    NEXT VALUE FOR BASIC_CUST_ID_SEQ,
    'First Name ' || NEXT VALUE FOR BASIC_CUST_ID_SEQ,
    'Last Name ' || NEXT VALUE FOR BASIC_CUST_ID_SEQ,
    'Address ' || NEXT VALUE FOR BASIC_CUST_ID_SEQ,
    'email' || NEXT VALUE FOR BASIC_CUST_ID_SEQ || '@example.com',
    '1234567890',
    ROUND(RANDOM() * (50000 - 10000) + 10000, 2),
    ROUND(RANDOM() * (100000 - 50000) + 50000, 2),
    ROUND(RANDOM() * 5),
    'Nominee ' || NEXT VALUE FOR BASIC_CUST_ID_SEQ,
    'Adhar' || NEXT VALUE FOR BASIC_CUST_ID_SEQ,
    'PAN' || NEXT VALUE FOR BASIC_CUST_ID_SEQ,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM INFORMATION_SCHEMA.SEQUENCES
WHERE SEQUENCE_NAME = 'BASIC_CUST_ID_SEQ'
LIMIT 50;

-- Insert data into EMP_DATA
INSERT INTO BUDDIGA_DEVELOPERS.EMP_DATA (EMP_ID, EMP_NAME, EMP_EMAIL, NO_OF_CUST_DEALT, NO_OF_SALES, COMM_ON_SLS, CRE_TS, UPDT_TS)
SELECT
    NEXT VALUE FOR EMP_ID_SEQ,
    'Employee ' || NEXT VALUE FOR EMP_ID_SEQ,
    'employee' || NEXT VALUE FOR EMP_ID_SEQ || '@example.com',
    ROUND(RANDOM() * (100 - 10) + 10),
    ROUND(RANDOM() * (100 - 10) + 10),
    ROUND(RANDOM() * (5000 - 1000) + 1000, 2),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM INFORMATION_SCHEMA.SEQUENCES
WHERE SEQUENCE_NAME = 'EMP_ID_SEQ'
LIMIT 10;

-- Insert data into CASE_TABLE
INSERT INTO BUDDIGA_DEVELOPERS.CASE_TABLE (CASE_ID, EMP_ID, CUST_ID, QUERY, CASE_PRGRS, CRE_TS, UPDT_TS)
SELECT
    NEXT VALUE FOR CASE_ID_SEQ,
    ROUND(RANDOM() * 10) + 1,
    ROUND(RANDOM() * 50) + 1,
    'Query ' || NEXT VALUE FOR CASE_ID_SEQ,
--    'Progress ' || NEXT VALUE FOR CASE_ID_SEQ,
    CASE WHEN ROUND(RANDOM()) = 0 THEN 'INPROGRESS' ELSE 'COMPLETED' END,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM INFORMATION_SCHEMA.SEQUENCES
WHERE SEQUENCE_NAME = 'CASE_ID_SEQ'
LIMIT 50;

-- Insert data into PROJECTS_DATA
INSERT INTO BUDDIGA_DEVELOPERS.PROJECTS_DATA (PRJCT_ID, PRJCT_NAME, PRJCT_ADDRESS, PRJCT_STATUS, PRJCT_POSESSION, NO_OF_TOWERS, NO_OF_FLOORS, PRJCT_AREA, TOTAL_NO_OF_APTS, NO_OF_APTS_SOLD, NO_OF_APTS_AVL, DIST_FRM_ARPT, DIST_FRM_RAIL, CRE_TS, UPDT_TS)
SELECT
    NEXT VALUE FOR PRJCT_ID_SEQ,
    'Project ' || NEXT VALUE FOR PRJCT_ID_SEQ,
    'Address ' || NEXT VALUE FOR PRJCT_ID_SEQ,
    CASE WHEN ROUND(RANDOM()) = 0 THEN 'ONGOING' ELSE 'COMPLETED' END,
    CURRENT_TIMESTAMP(),
    ROUND(RANDOM() * (10 - 1) + 1),
    ROUND(RANDOM() * (20 - 1) + 1),
    ROUND(RANDOM() * (5000 - 1000) + 1000, 2),
    ROUND(RANDOM() * (200 - 50) + 50),
    ROUND(RANDOM() * (100 - 20) + 20),
    ROUND(RANDOM() * (50 - 5) + 5),
    ROUND(RANDOM() * (50 - 10) + 10, 2),
    ROUND(RANDOM() * (50 - 10) + 10, 2),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM INFORMATION_SCHEMA.SEQUENCES
WHERE SEQUENCE_NAME = 'PRJCT_ID_SEQ'
LIMIT 50;

-- Insert data into PROPERTY_DATA
INSERT INTO BUDDIGA_DEVELOPERS.PROPERTY_DATA (PRPTY_ID, PRJCT_ID, PRPTY_SQ_FT_AREA, TYPE_OF_BHKS, PRICE_RANGE, PRPTY_FACING, CRE_TS, UPDT_TS)
SELECT
    NEXT VALUE FOR PRPTY_ID_SEQ,
    ROUND(RANDOM() * 50) + 1,
    ROUND(RANDOM() * (2000 - 500) + 500, 2),
    'Type' || NEXT VALUE FOR PRPTY_ID_SEQ,
    'Price Range' || NEXT VALUE FOR PRPTY_ID_SEQ,
    'Facing' || NEXT VALUE FOR PRPTY_ID_SEQ,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM INFORMATION_SCHEMA.SEQUENCES
WHERE SEQUENCE_NAME = 'PRPTY_ID_SEQ'
LIMIT 50;

-- Insert data into FUNDS_DATA
INSERT INTO BUDDIGA_DEVELOPERS.FUNDS_DATA (FUND_ID, PRJCT_ID, FUND_EST_TO_CMLT_PROJ, FUND_SPNT_TILL_DT, CRE_TS, UPDT_TS)
SELECT
    NEXT VALUE FOR FUND_ID_SEQ,
    ROUND(RANDOM() * 50) + 1,
    ROUND(RANDOM() * (500000 - 100000) + 100000, 2),
    ROUND(RANDOM() * (20000 - 10000) + 10000, 2),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM INFORMATION_SCHEMA.SEQUENCES
WHERE SEQUENCE_NAME = 'FUND_ID_SEQ'
LIMIT 50;

-- Insert data into SALES_DATA
INSERT INTO BUDDIGA_DEVELOPERS.SALES_DATA (SALE_ID, CUST_ID, EMP_ID, RVNUE_RCVD, RVNUE_YET_TO_COME, POSESSION_DATE_AGRD, CRE_TS, UPDT_TS)
SELECT
    NEXT VALUE FOR SALE_ID_SEQ,
    ROUND(RANDOM() * 50) + 1,
    ROUND(RANDOM() * 10) + 1,
    ROUND(RANDOM() * (50000 - 10000) + 10000, 2),
    ROUND(RANDOM() * (50000 - 10000) + 10000, 2),
    DATEADD('DAY', ROUND(RANDOM() * 365), CURRENT_DATE),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM INFORMATION_SCHEMA.SEQUENCES
WHERE SEQUENCE_NAME = 'SALE_ID_SEQ'
LIMIT 50;


--ALTER TABLE BUDDIGA_DEVELOPERS.CASE_TABLE ADD CONSTRAINT FOREIGN KEY (EMP_ID) REFERENCES EMP_DATA(EMP_ID)
--ON UPDATE SET NULL, ON DELETE SET NULL;
--ALTER TABLE BUDDIGA_DEVELOPERS.CASE_TABLE ADD CONSTRAINT  FOREIGN KEY (CUST_ID) REFERENCES BASIC_CUST_DATA(CUST_ID)
--ON UPDATE SET NULL, ON DELETE SET NULL;
--ALTER TABLE BUDDIGA_DEVELOPERS.SALES_DATA ADD CONSTRAINT FOREIGN KEY (CUST_ID) REFERENCES BASIC_CUST_DATA(CUST_ID)
--ON UPDATE SET NULL, ON DELETE SET NULL;
--ALTER TABLE BUDDIGA_DEVELOPERS.SALES_DATA ADD CONSTRAINT FOREIGN KEY (EMP_ID) REFERENCES EMP_DATA(EMP_ID)
--ON UPDATE SET NULL, ON DELETE SET NULL;
--ALTER TABLE BUDDIGA_DEVELOPERS.FUNDS_DATA ADD CONSTRAINT FOREIGN KEY (PRJCT_ID) REFERENCES PROJECTS_DATA(PRJCT_ID)
--ON UPDATE SET NULL, ON DELETE SET NULL;

